### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by devstorm321** [JanPoonthong/commerce#1]
@JanPoonthong hi, Jan. I wanna contribute to this project. Do you need my help?

**Comment by JanPoonthong** [comment]
Yes, I wanted to do microservices in Django connecting the Django with JavaScript, if you look at repo there porn_filter.js and server.js, I want to run them on heroku as microservices, so that django can request and know if the image is porn or not. Even better if there is a way to make like https://commercewebapp.herokuapp.com/ render django and https://commercewebapp.herokuapp.com/api/<whatever> give server.js(web API)

Let's chat on Discord: Jan#3423 <- add me

**Comment by devstorm321** [comment]
@JanPoonthong sorry, not Discord. Slack to me ddstorm0114@outlook.coom

**Comment by JanPoonthong** [comment]
Alright, I added

**Comment by devstorm321** [comment]
@JanPoonthong I did not receive your invitation on slack.

**Comment by JanPoonthong** [comment]
@devstorm321 I tried to add you, but I think you're gmail is wrong. Add me janpoonthong628@gmail.com
